# Generated by Django 5.0 on 2023-12-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('hotel', models.CharField(max_length=15)),
                ('chel', models.IntegerField()),
                ('price', models.IntegerField()),
                ('list', models.TextField()),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.countries')),
            ],
        ),
    ]
